version: "3.8"

services:
  app:
    container_name: s3corp-golang-fresher-app-dev
    image: s3corp-golang-fresher-go-dev:latest
    ports:
      - "5000:5000"
    restart: on-failure
    environment:
      APP_PORT: 5000
      DB_URL: "postgres://s3corp-golang-fresher:@db:5432/s3corp-golang-fresher?sslmode=disable"
    networks:
      - s3corp

  db:
    container_name: s3corp-golang-fresher-db-dev
    image: postgres:11-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: s3corp-golang-fresher
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - s3corp

  db-migrate:
    container_name: s3corp-golang-fresher-db-migrate-dev
    image: migrate/migrate:v4.15.1
    restart: "no"
    environment:
      DB_URL: "postgres://s3corp-golang-fresher:@db:5432/s3corp-golang-fresher?sslmode=disable"
    depends_on:
      - db
    volumes:
      - ./data/migrations:/migrations
    command: [ "-path", "/migrations", "-database" , "postgres://s3corp-golang-fresher:@db:5432/s3corp-golang-fresher?sslmode=disable" ,"up" ]
    networks:
      - s3corp

volumes:
  db:

networks:
  s3corp:
